# Dependencies

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:           the everything notebook
tagline:         'a digital record for my easily-distracted brain.'
description:      ''

paginate:         5

# Custom vars
version:          2.1.0

